<a href="https://colab.research.google.com/github/RohitBit-25/Al-ml-Colab/blob/main/Numpy_full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


List vs NumPy - Time Taken


In [ ]:
from time import process_time

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0010678569999997833


In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.0013256770000000806


Numpy Array

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
 # Creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
c = np.array ([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#creating identity matrix
a = np.eye(6)
print(a)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.42045668 0.85089472 0.96341587 0.06609326]
 [0.34471712 0.66653846 0.58443394 0.93041462]
 [0.32245074 0.92721875 0.80038664 0.88999861]]


In [ ]:
# create random numpy array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[23 79 49 84 14]
 [88 36 33 15 17]
 [70 25 88 74 11]]


In [ ]:
# array of evenly spaced values
d = np.linspace(10,300,6)
print(d)

[ 10.  68. 126. 184. 242. 300.]


In [ ]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
list2 = [10,20,20,20,50]
np_array = np.array(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[66 14 80 70 29]
 [72 16 79 43 25]
 [88 78 88 34 29]
 [87 25 58 30 61]
 [15 28 51 84 11]]


In [ ]:
print(c.shape)
print(c.ndim)
print(c.dtype)
print(c.size)
print(c.itemsize)

(5, 5)
2
int64
25
8


In [ ]:
a =  np.random.randint(10,90,(5,5))
b = np.random.randint(5,10,(5,5))
print(a)
print(b)

[[45 14 40 53 85]
 [44 57 85 14 34]
 [42 51 44 18 83]
 [13 58 29 18 45]
 [83 58 71 40 11]]
[[8 5 8 5 7]
 [7 5 8 7 9]
 [5 9 5 6 9]
 [6 9 8 7 7]
 [5 5 7 6 6]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[53 19 48 58 92]
 [51 62 93 21 43]
 [47 60 49 24 92]
 [19 67 37 25 52]
 [88 63 78 46 17]]
[[37  9 32 48 78]
 [37 52 77  7 25]
 [37 42 39 12 74]
 [ 7 49 21 11 38]
 [78 53 64 34  5]]
[[360  70 320 265 595]
 [308 285 680  98 306]
 [210 459 220 108 747]
 [ 78 522 232 126 315]
 [415 290 497 240  66]]
[[ 5.625       2.8         5.         10.6        12.14285714]
 [ 6.28571429 11.4        10.625       2.          3.77777778]
 [ 8.4         5.66666667  8.8         3.          9.22222222]
 [ 2.16666667  6.44444444  3.625       2.57142857  6.42857143]
 [16.6        11.6        10.14285714  6.66666667  1.83333333]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 2 0]
 [1 6 6]]
(2, 3)


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[0 1]
 [2 6]
 [0 6]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 1]
 [0 9 7]]
(2, 3)


In [ ]:
#using .t function
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 0]
 [9 9]
 [1 7]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 5 7]
 [3 3 4]]
(2, 3)
